# Generated by Django 3.1.5 on 2021-01-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_diplomathesis_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRealtors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('rating', models.CharField(max_length=150, verbose_name='Рейтинг')),
                ('year_of_foundation', models.PositiveSmallIntegerField(default=0, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Риэлторское агенство',
                'verbose_name_plural': 'Риэлторские агенства',
            },
        ),
        migrations.CreateModel(
            name='ContractPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to='uploads/', verbose_name='Контракт купли-продажи')),
            ],
            options={
                'verbose_name': 'Контракт купли-продажи',
                'verbose_name_plural': 'Данные о конктрактах купли-продаже',
            },
        ),
        migrations.CreateModel(
            name='ContractServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to='uploads/', verbose_name='Контракт на оказание услуг')),
            ],
            options={
                'verbose_name': 'Контракт купли-продажи',
                'verbose_name_plural': 'Данные о конктрактах купли-продаже',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Владелец недвижимости',
                'verbose_name_plural': 'Владелец недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Электронная почта')),
                ('rating', models.CharField(max_length=150, verbose_name='Рейтинг')),
                ('id_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.agencyrealtors', verbose_name='Риэлторское агенство')),
            ],
            options={
                'verbose_name': 'Риэлтор',
                'verbose_name_plural': 'Риэлторы',
            },
        ),
        migrations.CreateModel(
            name='RealtorServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип услуги')),
                ('id_realtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.realtors', verbose_name='Риэлтор')),
            ],
            options={
                'verbose_name': 'Риэлторская услуга',
                'verbose_name_plural': 'Риэлторские услуги',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость')),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RequestPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('status', models.CharField(max_length=150, verbose_name='Статус')),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.customer', verbose_name='Покупатель')),
                ('id_realty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.realty', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
            },
        ),
        migrations.CreateModel(
            name='TypeRealty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_realty', models.CharField(max_length=150, verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.RemoveField(
            model_name='events',
            name='id_employer',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='id_diploma',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='id_profession',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='id_employer',
        ),
        migrations.RemoveField(
            model_name='requestforpractice',
            name='id_practice',
        ),
        migrations.RemoveField(
            model_name='requestforpractice',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='id_graduate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='id_vacancy',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id_profession',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='id_employer',
        ),
        migrations.DeleteModel(
            name='DiplomaThesis',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Graduate',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='RequestForPractice',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Vacancies',
        ),
        migrations.AddField(
            model_name='realty',
            name='id_type_realty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.typerealty', verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='contractservices',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.owner', verbose_name='Владелец недвижимости'),
        ),
        migrations.AddField(
            model_name='contractservices',
            name='id_realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.realtors', verbose_name='Риэлтор'),
        ),
        migrations.AddField(
            model_name='contractservices',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.realtorservices', verbose_name='Риэлторская услуга'),
        ),
        migrations.AddField(
            model_name='contractpurchase',
            name='id_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.requestpurchase', verbose_name='Заявка на покупку'),
        ),
    ]
