# Generated by Django 3.1.5 on 2021-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_auto_20210128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpurchase',
            name='status',
            field=models.CharField(choices=[('rejected', 'Покупка не состоялась'), ('success', 'Покупка состоялась'), ('consideration', 'На рассмотрении')], max_length=150, verbose_name='Статус'),
        ),
    ]
