# Generated by Django 3.1.5 on 2021-01-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_auto_20210128_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpurchase',
            options={'verbose_name': 'Контракт купли-продажи', 'verbose_name_plural': 'Данные о контрактах купли-продаже'},
        ),
        migrations.AlterModelOptions(
            name='contractservices',
            options={'verbose_name': 'Контракт на оказание услуги', 'verbose_name_plural': 'Данные о контрактах на оказание услуги'},
        ),
    ]
